### ISSUE TITLE
Add additional members

### ISSUE THREAD

**Issue by ulpian** [Dodona/site#8]
Can we please add additional members on the website with their correct description and good image.

- My image and description will change;

New image;
![dsc06751](https://cloud.githubusercontent.com/assets/1069533/17784355/1f941ca0-6574-11e6-9df6-174fba03c9f2.JPG)
```
The programmer.
Linux / computer geek, tinkering is a virtue.

My job is ideas - to have a good tech spec and plan in place and lead founders to development. I also architect mainly the API, work with many different technologies to our apps and lead our teams.
```

- We will need to leave Eddie and his image / description.

+

- Add; Ifko Danev:

image;
![12695027_1157580410921492_7515670553012533855_o](https://cloud.githubusercontent.com/assets/1069533/17784566/df3a5812-6574-11e6-8d10-9626b3c68626.jpg)

```
The engineer.
Games, programming and hardware geek. Manager and Partner.

Aim to build things - responsible for drafting and architecting solutions and new ideas to internal and external products and help managers in development. Background in CGI and UX.
```

- Add; Leutrim Rexhepi:

image;
![leutrimi](https://cloud.githubusercontent.com/assets/1069533/17863131/5f398d94-6890-11e6-834b-3612beb410af.jpg)

```
Software engineer, technology enthusiast. Manager and Partner.

Focused on mobile - responsible for building native mobile applications, engineering new solutions to products, developing new ideas and managing products.
```

@donikajusufi i will add the same for @fatihdervisi - speak to him to get an image and description that looks the same as ours and can you add yourself too.

Add these as comments on this issue and I can confirm here :+1: 

We will also need to add new members like Gent and Valon when they join up :)

**can you crop and arrange the photos as they look best**

**Comment by donikajusufi** [comment]
Gent Berani: 

image;
![gentprof](https://cloud.githubusercontent.com/assets/20597727/17902440/b02825f8-6967-11e6-8d87-798cdddb7cd6.jpg)

Description :
Mobile Developer

I am  addicted to mobile apps, so the curiosity for them,  it affects me to push my self forward to start programming mobile applications. 
I love challenges, so first I started programming for Android. After a while I started developing apps also for iOS.
https://github.com/tneginareb

Donika Jusufi:

image;
![donikaprof](https://cloud.githubusercontent.com/assets/20597727/17902561/1586d96c-6968-11e6-9944-b3f2fc546434.jpg)

Description:
A Front-end developer
Client-side developer,modest but hard working.
Motivated to combine the art of design with the art of programming.Producing HTML,
CSS and JavaScript for a website or web application so that a user can see and interact with them directly.
https://github.com/donikajusufi

@ulpian check these please, I'm still waiting for @fatihdervisi  to send me his, since he is on vacation. 
Also what about Ifko , here at Dodona team on github  I can't find him , so I can put the link under the description?

**Comment by ulpian** [comment]
@donikajusufi 
Please also do not forget to add the names to the team members;

for Ifko; Ivaylo Danev https://github.com/ikoif
for Leutrim; Leutrim Rexhepi

I can confirm above :+1:

**Comment by donikajusufi** [comment]
Fatih Dervishi:

image;
![fatiprof](https://cloud.githubusercontent.com/assets/20597727/17938389/06787822-6a26-11e6-967a-1eb414880e96.png)

Software engineer  ,Java, Web Applications and Mobile Applications developer. 
Interested on algorithms and big-data. Innovations and new technology lover.
https://github.com/fatihdervisi

**Comment by ulpian** [comment]
@donikajusufi :+1: looking good.

**Comment by donikajusufi** [comment]
@ulpian  Okay I will proceed with the adding and changing the missing names .

**Comment by ulpian** [comment]
Completed via pull requests; #9 #10 

@donikajusufi please remember to reference the issue in the pull request in future :)
